# 1. Non-Postgres web services go here
services:
  - type: web
    name: q-connect
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn student_date.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qconnect-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

# 2. PostgreSQL databases must have their own top-level list
databases:
  - name: qconnect-db
    plan: free
    ipAllowList: []