# Generated by Django 6.0.7 on 2026-07-14 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('interested_in', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('residence', models.CharField(choices=[('qwetu_chiromo', 'Qwetu Chiromo'), ('qejani_chiromo', 'Qejani Chiromo'), ('qwetu_jogoo', 'Qwetu Jogoo Road'), ('qwetu_ruaraka', 'Qwetu Ruaraka'), ('qwetu_parklands', 'Qwetu Parklands'), ('qwetu_hurlingham', 'Qwetu Hurlingham'), ('qejani_hurlingham', 'Qejani Hurlingham'), ('qwetu_karen', 'Qwetu Karen'), ('qejani_karen', 'Qejani Karen')], max_length=30)),
                ('university', models.CharField(help_text='e.g. UoN, Strathmore, JKUAT', max_length=100)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pics/')),
                ('instagram_handle', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_likes', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
