# Generated by Django 6.0.7 on 2026-07-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_paid_chat_fee',
            field=models.BooleanField(default=False),
        ),
    ]
